### ISSUE TITLE
Email form in another view

### ISSUE THREAD

**Issue by mlabita37** [mlabita37/ScrapsNYC#1]
I'm having trouble getting my email signup form to work. The form is in an Angular template, and therefore I'm not sure how to get it's CRUD abilities from it's controller into the page. I tried to add ng-view to the <div> containing the form but that just gave me an infinite loop. I then tried adding the controller to the containing <div> using ng-controller, however, I'm getting a number of errors. One of the errors is a request error upon page load, though no request should be made until the form has been submitted. Then when I click submit, I'm getting a POST 404 error.  I think overall, this has to do with my organization. I've never used Angular templates before, but I do understand how they work. I'm thinking that the CRUD for the email can live app.js file along with my map rendering since they're all part of the same app. But if this is wrong, maybe I need to put the email CRUD into another file and declare a new Angular app that handles just the email? Not really sure how to organize/move forward on this one.

**Comment by ajhofferber** [comment]
Hey Mike, 

Are you still having this blocker at all? Or have you found a solution to it? Let us know if you're still stuck on it!

**Comment by mlabita37** [comment]
Hey Ash, sorry didn't see this earlier. Andrew helped me get the routing right this morning, which was a big part of it, and I fixed a few others related errors, but I'm still running into GET and POST errors and I can't figure out why. Would you be able to help me out still?
